#!/usr/bin/env zsh

# ls/exa aliases
alias ls="ls --color --group-directories-first"
alias l="ls -CF --color"
alias la="ls -ACF --color"
alias ll="ls -hlF --color"
alias lal="ls -hlAF --color"

alias se="sudoedit"

alias grep="grep --color"

z() {
  zathura "$@" > /dev/null 2>&1 &
}; compctl -/ -g '*.pdf' z

ze() {
  exec zathura "$@"
}
