#! /usr/bin/env zsh

# More paths
new_paths=("$HOME/bin" "$HOME/.local/bin" "$HOME/.cargo/bin" "$HOME/go/bin" "/usr/local/go/bin" "/home/linuxbrew/.linuxbrew/bin" "$HOME/.ghcup/bin")
for new_path in $new_paths;
    do [ -d $new_path ] && export PATH=$new_path:$PATH;
done
