import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.9
dynamic_padding = true
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "regular" }
size = 14

[keyboard]
bindings = [
  # { <key>, <mods>, <mode>, <action> | <chars> },
  { key="n", mods="Control | Shift", action="CreateNewWindow" },
]
